server:
  port=${PORT:8080}
hacktoberfest:
    repositories:
      - org: OpenElements
        repo: hedera-enterprise
      - org: OpenElements
        repo: hedera-solo-action


github:
  token: ${GITHUB_TOKEN:}


