server:
  port=${PORT:8080}
hacktoberfest:
    repositories:
      - org: ClyCites
        repo: ClyCites-Frontend
      - org: ClyCites
        repo: ClyCites-api

github:
  token: ${GITHUB_TOKEN:}


